{
	"title": "approve approval and BL throw exception",
	"task": "approve",
	"taskData": {
		"type": "approve",
		"id": "taskId",
		"approval": "caprizaApproval.json"
	},
	"steps": [
		{
			"func": "getBackendApproval",
			"args": [
				{
					"id": "approvalId"
				}
			],
			"output": [
				"caprizaApproval.json"
			]
		},
		{
			"func": "getApproval",
			"args": "caprizaApproval.json",
			"outputType": "Result.Success",
			"output": {
				"data": {
					"approval": "rawApproval.json"
				}
			}
		},
		{
			"func": "approve",
			"args": [
				{
					"approval": "caprizaApproval.json"
				},
				{}
			],
			"exception": "CONNECTOR_ERROR"
		},
		{
			"func": "updateTask",
			"args": [
				"taskId",
				{
					"status": "InternalError",
					"meta": {
						"entity": "sdk",
						"message": "Unexpected error: \"CONNECTOR_ERROR\"",
						"taskType": "approve"
					}
				}
			],
			"output": {}
		}
	]
}