{
	"title": "get attachment returns exception",
	"task": "getAttachment",
	"taskData": {
		"type": "getAttachment",
		"id": "attachment-0",
		"approval": {
			"id": "attachment-0",
			"metadata": {
				"fingerprints": {
					"sync": "10bad52d5b7b3772fe9c39d9cad8ba1302219876",
					"action": "38ea97eed8501d5144fc2604045f7185f9aed339"
				}
			},
			"public": {},
			"private": {
				"id": "082a0c7adba52200a6a2b31be0b8f5df",
				"approver": "christen.mitchell@example.com"
			}
		},
		"volatile": {
			"attachmentId": "fa8c86a6db62130037227d9ebf9619f0"
		}
	},
	"steps": [
		{
			"func": "downloadAttachment",
			"args": [
				{
					"attachmentId": "fa8c86a6db62130037227d9ebf9619f0",
					"approval": {
						"id": "attachment-0",
						"metadata": {
							"fingerprints": {
								"sync": "10bad52d5b7b3772fe9c39d9cad8ba1302219876",
								"action": "38ea97eed8501d5144fc2604045f7185f9aed339"
							}
						},
						"public": {},
						"private": {
							"id": "082a0c7adba52200a6a2b31be0b8f5df",
							"approver": "christen.mitchell@example.com"
						}
					}
				},
				{}
			],
			"exception": "CONNECTOR_ERROR"
		},
		{
			"func": "updateTask",
			"args": [
				"attachment-0",
				{
					"status": "InternalError",
					"meta": {
						"entity": "sdk",
						"message": "Unexpected error: \"CONNECTOR_ERROR\"",
						"taskType": "getAttachment"
					}
				}
			]
		}
	]
}